CarCamping-hanium/CarCamping_BackEnd

src/main/java/com/Hanium/CarCamping/Domain/CampSite.java, src/main/java/com/Hanium/CarCamping/Domain/Review.java
=> 차박지,리뷰 엔티티 개발

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/Hanium/CarCamping/CarCampingApplication.java, src/main/java/com/Hanium/CarCamping/config/security/UserDetailsServiceImpl.java, src/main/java/com/Hanium/CarCamping/config/security/WebSecurityConfig.java, src/main/java/com/Hanium/CarCamping/config/security/filter/AccessDeniedHandlerCustom.java, src/main/java/com/Hanium/CarCamping/config/security/filter/AuthenticationEntryPointCustom.java, src/main/java/com/Hanium/CarCamping/config/security/filter/DuplicatedEmailException.java, src/main/java/com/Hanium/CarCamping/config/security/filter/JwtAuthenticationFilter.java, src/main/java/com/Hanium/CarCamping/config/security/filter/WrongPasswordException.java, src/main/java/com/Hanium/CarCamping/config/security/jwt/BusinessLogicException.java, src/main/java/com/Hanium/CarCamping/config/security/jwt/ErrorCodeType.java, src/main/java/com/Hanium/CarCamping/config/security/jwt/JwtService.java, src/main/java/com/Hanium/CarCamping/config/security/jwt/MemberNotFoundException.java, src/main/java/com/Hanium/CarCamping/config/security/jwt/UserDefineException.java, src/main/java/com/Hanium/CarCamping/controller/member/memberController.java, src/main/java/com/Hanium/CarCamping/domain/dto/member/UpdateDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/member/createDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/member/getDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/member/signInDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/member/Member.java, src/main/java/com/Hanium/CarCamping/domain/entity/member/Role.java, src/main/java/com/Hanium/CarCamping/repository/MemberRepository.java, src/main/java/com/Hanium/CarCamping/service/member/MemberCreateService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberSignInService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberUpdateService.java, src/main/resources/application.yml
=> 차박지 /시큐리티 로그인/회원가입

build.gradle, src/main/java/com/Hanium/CarCamping/Exception/NoSuchCampSiteException.java, src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/controller/review/reviewController.java, src/main/java/com/Hanium/CarCamping/domain/Region.java, src/main/java/com/Hanium/CarCamping/domain/Tier.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/CreateCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCampSiteListDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/response/ListResult.java, src/main/java/com/Hanium/CarCamping/domain/dto/response/Result.java, src/main/java/com/Hanium/CarCamping/domain/dto/response/SingleResult.java, src/main/java/com/Hanium/CarCamping/domain/dto/review/CreateReviewDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/review/ResponseReviewDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review_Member.java, src/main/java/com/Hanium/CarCamping/domain/entity/member/Member.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/repository/ReviewMemberRepository.java, src/main/java/com/Hanium/CarCamping/repository/ReviewRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/Reponse/ResponseService.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java, src/main/java/com/Hanium/CarCamping/service/Review_Member/ReviewMemberService.java
리뷰에 기능에 대해서 개발했습니다.
Member Entity에  일대다 관계 추가했습니다.(review평가에 참가했는지 보기위해)
@OneToMany(mappedBy = "writer", cascade = CascadeType.ALL)
private List<Review> reviewList = new ArrayList<>();
반환형은 나중에 통일하는걸로 하는게 좋을 것 같습니다.
=> 리뷰 기능 관련 개발

src/main/java/com/Hanium/CarCamping/Exception/AlreadyParticipateException.java, src/main/java/com/Hanium/CarCamping/controller/Review_Member/Review_MemberController.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review_Member.java, src/main/java/com/Hanium/CarCamping/repository/ReviewMemberRepository.java, src/main/java/com/Hanium/CarCamping/service/Review_Member/ReviewMemberService.java
=> 리뷰 추천/비추천 기능 개발

build.gradle, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCampSiteListDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review.java, src/main/java/com/Hanium/CarCamping/repository/ReviewMemberRepository.java, src/main/java/com/Hanium/CarCamping/service/Review_Member/ReviewMemberService.java, src/main/resources/application.yml
Review_Member Repository 오류 해결 및 MariaDB 연동
=> Review_Member Repository 오류 해결 및 MariaDB 연동

src/main/java/com/Hanium/CarCamping/controller/member/memberController.java
닉네임 , 로그인 아이디 중복 확인 API 추가
있으면 true
없으면 false값 반환
=> 닉네임 , 로그인 아이디 중복 확인 API 추가

src/main/java/com/Hanium/CarCamping/controller/member/memberController.java
=> API 메서드 수정

src/main/java/com/Hanium/CarCamping/controller/Review_Member/Review_MemberController.java, src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/controller/member/memberController.java, src/main/java/com/Hanium/CarCamping/controller/ranking/RedisRankingController.java, src/main/java/com/Hanium/CarCamping/controller/review/reviewController.java, src/main/java/com/Hanium/CarCamping/domain/dto/member/ResponseMyInfoDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/member/UpdateNickNameDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/member/UpdatePasswordDto.java, src/main/java/com/Hanium/CarCamping/service/member/MemberCreateService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberDeleteService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberUpdateService.java
회원 정보 수정 및 비밀번호 수정 API 개발
서비스단에@Transactional 관련 에러 해결
=> 회원 정보 수정 및 비밀번호 수정 API 개발 및 코드 리팩토링

src/main/java/com/Hanium/CarCamping/controller/member/memberController.java, src/main/java/com/Hanium/CarCamping/service/member/MemberDeleteService.java
=> 회원 삭제 관련 검증 방식 추가

src/main/java/com/Hanium/CarCamping/service/member/MemberCreateService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberDeleteService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberUpdateService.java
회원 가입하자마자 랭킹서버에 들어가도록 변경
회원 닉네임 수정이 있을시 닉네임에 따라서 변경
회원 삭제시 같이 삭제되도록 변경
=> Redis 랭킹서버에서 회원에 대한 변경사항이 있을시 같이 변경되도록 수정

src/main/java/com/Hanium/CarCamping/controller/ranking/RedisRankingController.java
동점자가 있을때 동점자중 순위가 가장 높은사람 순위로 반환하도록 수정
=> 동점자 관련 순위 조정 기능 추가

src/main/java/com/Hanium/CarCamping/domain/dto/campsite/CreateCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java
차박지 엔티티에 편의시설 필드 추가
차박지 등록 DTO에 Score 있던 것 삭제 후 편의시설 추가
=> 편의시설 필드 추가 및 DTO 수정

build.gradle, src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/controller/member/memberController.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/CreateCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java, src/main/java/com/Hanium/CarCamping/service/Review_Member/ReviewMemberService.java, src/main/resources/application.yml
=> 차박지 campsite api 지오코딩 추가

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java
=> 지오코딩 코드 리팩토링

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCoordinateDto.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java
=> 차박지 지도활용을 위한 차박지 좌표값 반환  API 및 DTO 개발

.gitignore, build.gradle, src/main/java/com/Hanium/CarCamping/Exception/advice/CustomExceptionHandler.java, src/main/java/com/Hanium/CarCamping/config/security/AmazonS3Config.java, src/main/java/com/Hanium/CarCamping/config/security/WebSecurityConfig.java, src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/controller/image/ImageUploadController.java, src/main/java/com/Hanium/CarCamping/controller/member/memberController.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/CreateCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/domain/entity/member/Member.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/S3Service/S3Uploader.java, src/main/java/com/Hanium/CarCamping/service/member/MemberUpdateService.java, src/main/resources/application.yml
S3 연동작업 및 Security 파일 분리
코드 리팩토링
이미지 업로드 API 개발 및 프로필 사진 변경 API 추가
=> S3 연동 작업 및 기타 API 추가

src/main/java/com/Hanium/CarCamping/controller/Review_Member/Review_MemberController.java, src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/controller/review/reviewController.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/Point/PointService.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java, src/main/java/com/Hanium/CarCamping/service/Review_Member/ReviewMemberService.java, src/main/resources/application.yml
JPA 트랜잭션 밖에서 Member를 가져와서 영속성컨텍스트에서 찾을 수 없는 문제가 있었음
Transaction 안으로 넣어서 서비스 단에서 해결
=> no session 문제 해결을 위한 코드 리팩토링

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/domain/Region.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/RegionDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseCoordinateDto.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java
Enum 지역별 좌표값반환
lat과 lng값이 같이나오던 에러 수정
=> 지역별 좌표반환 API 개발 및 좌표 에러 수정

src/main/java/com/Hanium/CarCamping/domain/dto/review/CreateReviewDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/review/ResponseReviewDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review.java
=> 리뷰도 사진등록이 가능하도록 엔티티 및 DTO 수정

src/main/java/com/Hanium/CarCamping/controller/member/memberController.java, src/main/java/com/Hanium/CarCamping/domain/dto/review/ResponseOneReviewDto.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java
내 차박지,리뷰정보 조회 기능 추가 및 리뷰 단건조회 DTO 추가
=> 내 차박지,리뷰정보 조회 기능 추가 및 리뷰 단건조회 DTO 추가

src/main/java/com/Hanium/CarCamping/controller/member/memberController.java, src/main/java/com/Hanium/CarCamping/domain/dto/response/ListResult.java, src/main/java/com/Hanium/CarCamping/domain/dto/response/SingleResult.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java
=> JPA 트랜잭션 관련 No session 문제 해결

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java
Reverts CarCamping-hanium/CarCamping_BackEnd#48
fetch를 안하고 작업하셔서 이전 내용이 날라간후 덮어써짐
=> Revert "차박지 carcamp 최신,오래된,평점낮은수 api 추가"

src/main/java/com/Hanium/CarCamping/CarCampingApplication.java, src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java
=> 다양한 검색 및 정렬기능 추가

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/test/java/com/Hanium/CarCamping/service/CampSite/CampsiteServiceTest.java
차박지 회원객체  Lazy로딩으로 성능최적화
차박지 포함단어로 검색기능 API 추가
=> 차박지 포함단어로 검색기능 API 추가

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/test/java/com/Hanium/CarCamping/service/CampSite/CampsiteServiceTest.java
=> 단어로 검색 API 점수순으로 정렬 반환

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/test/java/com/Hanium/CarCamping/service/CampSite/CampsiteServiceTest.java
=> Revert "단어로 검색 API 점수순으로 정렬 반환"

src/main/java/com/Hanium/CarCamping/controller/campSite/CampSiteController.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/FindCampSiteDto.java, src/main/java/com/Hanium/CarCamping/repository/CampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/test/java/com/Hanium/CarCamping/service/CampSite/CampsiteServiceTest.java
=> 검색 API 세분화

src/main/java/com/Hanium/CarCamping/Exception/NoSuchWaitingCampSiteException.java, src/main/java/com/Hanium/CarCamping/controller/waitingCampSite/WaitingCampSiteController.java, src/main/java/com/Hanium/CarCamping/domain/dto/waitingcampsite/ResponseWaitingCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/waitingcampsite/ResponseWaitingCampSiteListDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/domain/entity/WaitingCampSite.java, src/main/java/com/Hanium/CarCamping/repository/WaitingCampSiteRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/WaitingCampSite/WaitingCampSiteService.java, src/main/resources/application.yml
=> 차박지 즉시 등록방식-> 차박지 등록 대기 방식으로 변경

src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java, src/main/java/com/Hanium/CarCamping/service/Review_Member/ReviewMemberService.java, src/main/java/com/Hanium/CarCamping/service/WaitingCampSite/WaitingCampSiteService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberCreateService.java, src/test/java/com/Hanium/CarCamping/service/CampSite/CampsiteServiceTest.java, src/test/java/com/Hanium/CarCamping/service/Member/adminMemberCreateService.java
=> Admin 계정은 Redis에서 제외

src/main/java/com/Hanium/CarCamping/domain/entity/member/Member.java
point,review 엔티티
orphanRemoval 설정 추가
=> orphanRemoval 설정 추가

src/test/java/com/Hanium/CarCamping/service/Member/createAdminTest.java
=> admin 추가 테스트

src/main/java/com/Hanium/CarCamping/controller/ranking/RedisRankingController.java, src/main/java/com/Hanium/CarCamping/service/Point/PointService.java, src/main/java/com/Hanium/CarCamping/service/Ranking/RankingService.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java, src/main/java/com/Hanium/CarCamping/service/Review_Member/ReviewMemberService.java, src/main/java/com/Hanium/CarCamping/service/WaitingCampSite/WaitingCampSiteService.java
=> Redis 코드 리펙토링

src/main/java/com/Hanium/CarCamping/Exception/advice/CustomExceptionHandler.java, src/main/java/com/Hanium/CarCamping/Exception/alreadyReportReviewException.java, src/main/java/com/Hanium/CarCamping/controller/review/reviewController.java, src/main/java/com/Hanium/CarCamping/domain/dto/review/ResponseReportReviewDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review_Member.java, src/main/java/com/Hanium/CarCamping/domain/entity/member/Member.java, src/main/java/com/Hanium/CarCamping/repository/ReviewRepository.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/Ranking/RankingService.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java, src/main/java/com/Hanium/CarCamping/service/member/MemberCreateService.java, src/test/java/com/Hanium/CarCamping/service/CampSite/CampsiteServiceTest.java
1.리뷰 신고기능추가
2,리뷰 신고 중복 참가 불가
3.admin 신고된 리뷰목록 받아보기 및 리뷰 삭제 및 통과 기능 추가
4.admin 모든 리뷰 삭제 권한 추가
=> 리뷰 신고기능 추가 및 관련기능 업데이트

src/main/java/com/Hanium/CarCamping/domain/entity/Report_Member.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review.java, src/main/java/com/Hanium/CarCamping/repository/ReportMemberRepository.java, src/main/java/com/Hanium/CarCamping/service/Report_Member/ReportMemberService.java, src/main/java/com/Hanium/CarCamping/service/Review/ReviewService.java
Report Member 를 통한 중복관리 및 신고관리
=> Report Member 엔티티 추가 및 업데이트

src/main/java/com/Hanium/CarCamping/domain/entity/Report_Member.java, src/main/java/com/Hanium/CarCamping/domain/entity/Review.java, src/main/resources/application.yml, src/test/java/com/Hanium/CarCamping/service/Member/createAdminTest.java
=> mappedBy 칼럼 오류 해결

src/main/java/com/Hanium/CarCamping/Exception/NoSuchChangeRequestException.java, src/main/java/com/Hanium/CarCamping/Exception/advice/CustomExceptionHandler.java, src/main/java/com/Hanium/CarCamping/controller/ChangeCampSite/ChangeCampSiteController.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ChangeCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseChangeCampSiteDto.java, src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseChangeCampSiteListDto.java, src/main/java/com/Hanium/CarCamping/domain/entity/CampSite.java, src/main/java/com/Hanium/CarCamping/domain/entity/ChangeCampSite.java, src/main/java/com/Hanium/CarCamping/service/CampSite/CampsiteService.java, src/main/java/com/Hanium/CarCamping/service/ChangeCampSite/ChangeCampSiteService.java
차박지 수정기능 추가
수정 엔티티 추가
수정 승인,거부 기능 추가
admin은 바로 수정될 수 있도록 함
=> 차박지 수정기능 추가

src/main/java/com/Hanium/CarCamping/domain/dto/campsite/ResponseChangeCampSiteListDto.java
=> ListDto에도 address값 나오도록 변경
